name: Actions Workflow

on: [push, pull_request]

jobs: 
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: List Files Before Checkout
        run: |
          pwd
          ls -la
          echo "GITHUB SHA : "$GITHUB_SHA
          echo "GITHUB_REPOSITORY : "$GITHUB_REPOSITORY
          echo "GITHUB_WORKSPACE : "$GITHUB_WORKSPACE
          echo "github.token : ${{ github.token }}"
      - name: Checkout
        uses: actions/checkout@v1
      - name: List Files After Checkout
        run: |
          pwd
          ls -la
      - name: Simple JS Action
        id: greet
        uses: actions/hello-world-javascript-action@v1
        with: 
          who-to-greet: Tony
      - name: Log Greeting Time
        run: echo "${{ steps.greet.outputs.time}}"
